##########################################################################################
general:
  TSParams_FilePath: /home/kwtsang/romhunter/ROMOutput/enriched_trainingset.txt
  modelName: IMRPhenomPv2FD
  modelTag:  hp
  outputdir: /home/kwtsang/romhunter/ROMOutput
  # These will be used to calculate the frequency vector by either uniform sampling with sampling points (fmax-fmin)*seglen+1 or multibanding.
  # To use uniform sampling, please specify "bands:[]", fmin, fmax and seglen.
  # To use multibanding, please specify bands, fudge and Mc-min.
  fmin: 20
  fmax: 2048
  seglen: 32
  bands: [  20,   30,   40,   50,   60,   70,   80,   90,  100,  110,  120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,  230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,  340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,  450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,  560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,  670, 680,  690,  700,  710,  720,  730,  740,  750,  760,  770,  780, 790,  800,  810,  820,  830,  840,  850,  860,  870,  880,  890, 900,  910,  920,  930,  940,  950,  960,  970,  980,  990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560, 1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650, 1660, 1670, 1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780, 1790, 1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020, 2030, 2040, 2048]
  fudge: 5
  Mc-min: 3.4

  # a sequence indicating the corresponding variable name in the final trainingset file
  columnSequence:
    - m1
    - m2
    - chi1L
    - chi2L
    - chip
    - thetaJ
    - alpha0
    - zero
    - dchi0
    - dchi1
    - dchi2
    - dchi3
    - dchi4
    - dchi5l
    - dchi6
    - dchi6l
    - dchi7
    - dalpha2
    - dalpha3
    - dalpha4
    - dbeta2
    - dbeta3
    - dsigma2
    - dsigma3
    - dsigma4

  # origin of params, can be from TSParams_FilePath or random number.
  # available method are "file", "uniform". "chebyshev", "zero".
  #   for method == "file", please specify column
  #   for method != "file", please specify min, max, numberOfPoints
  paramsDict:
    zero: &ZERO
      method: zero
      min: 0
      max: 0
      numberOfPoints: 1
    m1:
      method: file
      column: 1
    m2:
      method: file
      column: 2
    chi1L:
      method: file
      column: 3
    chi2L:
      method: file
      column: 4
    chip:
      method: file
      column: 5
    thetaJ:
      method: file
      column: 6
    alpha0:
      method: file
      column: 7
    dchi0:
      <<: *ZERO
    dchi1:
     #<<: *ZERO
      method: file
      column: 10
    dchi2:
      <<: *ZERO
    dchi3:
      <<: *ZERO
    dchi4:
      <<: *ZERO
    dchi5l:
      <<: *ZERO
    dchi6:
      <<: *ZERO
    dchi6l:
      <<: *ZERO
    dchi7:
      <<: *ZERO
    dbeta2:
      <<: *ZERO
    dbeta3:
      <<: *ZERO
    dalpha2:
      <<: *ZERO
    dalpha3:
      <<: *ZERO
    dalpha4:
      <<: *ZERO
      #method: file
      #column: 20
    dsigma2:
      <<: *ZERO
    dsigma3:
      <<: *ZERO
    dsigma4:
      <<: *ZERO

###########################################################################################
greedy:
  toleranceGreedy: 1e-12
  maxRB: 50000

###########################################################################################
EIM:

###########################################################################################
validation:
  tolerance: 1e-8
  numberOfPoints: 20000
  Vinv_FilePath:      /home/kwtsang/romhunter/ROMOutput/Vinv.npy
  Bkf_FilePath:       /home/kwtsang/romhunter/ROMOutput/Bkf.npy
  RBMatrix_FilePath:  /home/kwtsang/romhunter/ROMOutput/orthonormalRB.npy
  EIMStdout_FilePath: /home/kwtsang/romhunter/ROMOutput/EIMStdout.txt

  randParamsRangeDict:
    kerrBound: 0.98
    Mc:
      min: 3.4
      max: 6.2
      method: chebyshev
    q:
      min: 1.0
      max: 9.0
      method: chebyshev
    m1:
      min: 1.0
      max: 1.0
      method: qMc
    m2:
      min: 1.0
      max: 1.0
      method: qMc
    chi1L:
      min: -0.9
      max: 0.9
      method: uniform
    chi2L:
      min: -0.9
      max: 0.9
      method: uniform
    chip:
      min: 0.0
      max: 0.9
      method: uniform
    thetaJ:
      min: 0.0
      max: 3.14159265
      method: uniform
    alpha0:
      min: 0.0
      max: 6.28318531
      method: uniform
    dchi0:
      <<: *ZERO
    dchi1:
     # <<: *ZERO
      min: -10.0
      max: 10.0
      method: uniform
    dchi2:
      <<: *ZERO
    dchi3:
      <<: *ZERO
    dchi4:
      <<: *ZERO
    dchi5l:
      <<: *ZERO
    dchi6:
      <<: *ZERO
    dchi6l:
      <<: *ZERO
    dchi7:
      <<: *ZERO
    dbeta2:
      <<: *ZERO
    dbeta3:
      <<: *ZERO
    dalpha2:
      <<: *ZERO
    dalpha3:
      <<: *ZERO
    dalpha4:
      <<: *ZERO
      #min: -10.0
      #max: 10.0
      #method: chebyshev
    dsigma2:
      <<: *ZERO
    dsigma3:
      <<: *ZERO
    dsigma4:
      <<: *ZERO
    zero:
      <<: *ZERO


